export default {
    LOGIN_LOADING: 'LOGIN_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    UPLOAD_AVATAR_LOADING: 'UPLOAD_AVATAR_LOADING',
    UPLOAD_AVATAR_SUCCESS: 'UPLOAD_AVATAR_SUCCESS',
    UPLOAD_AVATAR_FAIL: 'UPLOAD_AVATAR_FAIL',

    UPLOAD_USER_SEX_LOADING: 'UPLOAD_USER_SEX_LOADING',
    UPLOAD_USER_SEX_SUCCESS: 'UPLOAD_USER_SEX_SUCCESS',

    UPLOAD_USER_NAME_LOADING: 'UPLOAD_USER_NAME_LOADING',
    UPLOAD_USER_NAME_SUCCESS: 'UPLOAD_USER_NAME_SUCCESS',
};

